### ISSUE TITLE
Please support Huawei P10 based EMUI8.0

### ISSUE THREAD

**Issue by Coconutat** [reiryuki/AudioFX-LineageOS-Magisk-Module#1]
Magsik Version：20.4
OS：EMUI 8.0
Andorid Version：8.0.0
Device：Huawei P10
I use Magisk Manager to flash the Zip package，but when I reboot my phone，the AudioFX Application I can’t run.When I open it，the application will  shuts down automatically.

**Comment by reiryuki** [comment]
read and do this https://t.me/androidryukimodsdiscussions/2618

**Comment by Coconutat** [comment]
> read and do this https://t.me/androidryukimodsdiscussions/2618

EMUI 8 can’t setenforce 0,so I can’t send you prem.txt.if I want change selinux mode,I must modify kernel,but only huawei have source code.Looks like I don’t have choice except give up.

**Comment by reiryuki** [comment]
just ignore it and do bug report

**Comment by Coconutat** [comment]
> just ignore it and do bug report

OK，
here is Magisk install log
[magisk_install_log_2021-10-21T22:23:29Z.log](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7390136/magisk_install_log_2021-10-21T22.23.29Z.log)

here is logcat
[logcat_10-21-2021_22-26-18.txt](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7390110/logcat_10-21-2021_22-26-18.txt)

here is zip file
1. for all module 
[all module.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7390163/all.module.zip)

2. others
[z.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7390175/z.zip)

Hope it work...🐶

**Comment by reiryuki** [comment]
Exclude AudioFX app from your EdXposed list (blacklist it)

**Comment by Coconutat** [comment]
> Exclude AudioFX app from your EdXposed list (blacklist it)

Ok,I blacklist it now.Then I open AudioFX,still doesn't work.App still flashback.Can’t use.Reboot device is same too.

**Comment by reiryuki** [comment]
disable any other modules, including edxposed, resend bug report

**Comment by Coconutat** [comment]
> disable any other modules, including edxposed, resend bug report

Ok.I do it again.I disable all modules.Nothing is
 Enable.
Here is logcat:
[logcat_10-22-2021_17-40-48.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7396132/logcat_10-22-2021_17-40-48.zip)
I don't want to zip it.But github don't allow me upload original file.

Here is zip files:
1.For all modules
[1.For All Modules.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7396150/1.For.All.Modules.zip)

2.Others
[2.others.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7396152/2.others.zip)

**Comment by reiryuki** [comment]
nothing is detected about audiofx in your latest logcat. did you open reopen turn off turn on the audiofx and play music while taking logcat?

**Comment by reiryuki** [comment]
if not then do it like that and resend the logcat only

**Comment by Coconutat** [comment]
> if not then do it like that and resend the logcat only

Emmm...I don’t open.
This logcat is I enable AudioFX in Magisk and reboot my device.Then I open poweramp playing muisc.Hope can help you.
[logcat_10-22-2021_22-09-34.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7398172/logcat_10-22-2021_22-09-34.zip)

**Comment by reiryuki** [comment]
@Coconutat
Try this beta 1
changelog:
- Changed dex version to 035 for compatibility
- Script enhancement
[AudioFX-LineageOS.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7638712/AudioFX-LineageOS.zip)

**Comment by Coconutat** [comment]
> 

OK,I will try it today.

**Comment by Coconutat** [comment]
> @Coconutat Try this beta 1 changelog:
> 
>     * Changed dex version to 035 for compatibility
> 
>     * Script enhancement
>       [AudioFX-LineageOS.zip](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module/files/7638712/AudioFX-LineageOS.zip)
Thank you very much for your patience and kindness. Thank you for your efforts. The function works well, very good. Although the built-in equalizer of poweramp ignores audio FX, apps such as Netease cloud can be used.

**Comment by Coconutat** [comment]
I will remember what you have done for this. Thank you very much.

**Comment by reiryuki** [comment]
Welcome 🙂👍
