### ISSUE TITLE
[Bug report]AudioFX-LineageOS-Magisk-Module v2.1 beta 1 some bugs

### ISSUE THREAD

**Issue by Coconutat** [reiryuki/AudioFX-LineageOS-Magisk-Module#2]
Magsik Version：20.4
OS：EMUI 8.0
Andorid Version：8.0.0
Device：Huawei P10
First of all, I would like to thank you for your great efforts to adapt my equipment.But unfortunately, there were some unexpected bugs.
So,here is I konwn bugs list.
Bugs:
1.Sometimes system will tip 'Application not responding' when I use AudioFX.
2.Destroy camera function.If I use v2.1 beta 1 module,the camera will disable and never can enable.Unless I uninstall this module.(Even flashlight function is can't enable too.)[Will,This bug really bothers me because I can't scan the QR code.]
3.When I play music in background mode,playing music will crash or stop.Unless I replay it or unlock my screen lock.
If you want any else,or some I can do.Please tell me.I'll be back in a few days. I'm sorry about that. I may be a little busy these days.

**Comment by reiryuki** [comment]
Read bug report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, it will be closed immediately
