### ISSUE TITLE
[TESTED] working on miui 11

### ISSUE THREAD

**Issue by SayaAEP** [reiryuki/AudioFX-LineageOS-Magisk-Module#3]
os: Android 9 sdk 29 (?)
distro: MIUI 11
type: Redmi 6A
manufacture: Xiaomi
magisk: 25.2 and 25.2 delta [HuskyDG/magisk-files](https://github.com/HuskyDG/magisk-files) (magisk delta are for emulators and android x86 so i installed to android x86 and phone for testing)
props: optionals.prop none changed
aml installed: true
MusicFX installed: true

full working functionality [AudioFX](https://github.com/reiryuki/AudioFX-LineageOS-Magisk-Module) except echo toggle. the volume is low like 10% when the volume level is around 50%

<details>
  <summary>hmm</summary>
  
  ### Heading
this is my fav equalizer
</details>

**Comment by sayaaep** [comment]
open equalizer from spotify: true working
